#Requires -Version 5.1
<#
.SYNOPSIS
    Installs just Android platform-tools (adb) -- the minimum needed to sideload.
.DESCRIPTION
    About 10 MB, no SDK, no NDK. Lands in the same toolchain layout that
    01-setup-toolchain.ps1 uses, so 03-sideload-firetv.ps1 finds adb either way.
#>
[CmdletBinding()]
param(
    [string]$ToolchainRoot = 'D:\android-toolchain'
)

$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'

$Url         = 'https://dl.google.com/android/repository/platform-tools-latest-windows.zip'
$Downloads   = Join-Path $ToolchainRoot 'downloads'
$SdkRoot     = Join-Path $ToolchainRoot 'android-sdk'
$PlatformTools = Join-Path $SdkRoot 'platform-tools'
$ProjectRoot = Split-Path -Parent $PSScriptRoot

function Write-Step { param([string]$Message) Write-Host "`n==> $Message" -ForegroundColor Cyan }

New-Item -ItemType Directory -Force -Path $Downloads, $SdkRoot | Out-Null

$zip = Join-Path $Downloads 'platform-tools-latest-windows.zip'
if (-not (Test-Path $zip)) {
    Write-Step 'Downloading Android platform-tools (~10 MB)'
    Invoke-WebRequest -Uri $Url -OutFile $zip -UseBasicParsing
}
$mb = [math]::Round((Get-Item $zip).Length / 1MB, 1)
Write-Host "  $zip ($mb MB)"

if (-not (Test-Path (Join-Path $PlatformTools 'adb.exe'))) {
    Write-Step 'Unpacking'
    $staging = Join-Path $Downloads 'staging-platform-tools'
    if (Test-Path $staging) { Remove-Item -Recurse -Force $staging }
    Expand-Archive -Path $zip -DestinationPath $staging -Force
    if (Test-Path $PlatformTools) { Remove-Item -Recurse -Force $PlatformTools }
    Move-Item -Path (Join-Path $staging 'platform-tools') -Destination $PlatformTools
    Remove-Item -Recurse -Force $staging
}

# Only write the env file if the full toolchain setup has not already made one.
$envScript = Join-Path $ProjectRoot 'toolchain-env.ps1'
if (-not (Test-Path $envScript)) {
    @"
# Generated by scripts\00a-get-adb.ps1 -- adb only, no SDK/NDK yet.
`$env:ANDROID_HOME     = '$SdkRoot'
`$env:ANDROID_SDK_ROOT = '$SdkRoot'
`$env:PATH             = '$PlatformTools;' + `$env:PATH
"@ | Set-Content -Path $envScript -Encoding utf8
}

Write-Step 'adb ready'
& (Join-Path $PlatformTools 'adb.exe') version
